### ISSUE TITLE
SourceKit crashes on Xcode 9 after adding MathPixClient

### ISSUE THREAD

**Issue by vdharankar** [Mathpix/ios-client#2]
Tried MathPixClient on Xcode 9, the swift version was set to 3.2, each time I edited the code SourceKit crashed repeatedly leaving it unusable , though it builds fine and runs fine, can you check ?

**Comment by DmitriDevelopment** [comment]
I checked on Xcode 9 swift 3.2. Crashed with error: "This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data." Xcode 8 didn't crash with this error.
Need to add NSCameraUsageDescription ket to app's info.plist, after it app runs fine on my device. If you have other error I need more info.

**Comment by vdharankar** [comment]
I think you didn't try editing anything in the code, try adding some code using autocomplete and you will see source kit crash. I don't have issue with app running .

**Comment by DmitriDevelopment** [comment]
thanks for the clarification, there really is such a problem. I don't know yet what is it, I'll figure out this issue

**Comment by DmitriDevelopment** [comment]
looks like a bug of Xcode 9. I reported a bug to Apple. Any results will be reported here. If the apple does not solve the problem to the end of this week I'll try recreate pod from scratch. Sorry, I have no time to do it right now.

**Comment by vdharankar** [comment]
Ok np , i ended up calling API directly for now, will look forward to this however. Thanks

**Comment by DmitriDevelopment** [comment]
I fixed this issue, the problem was in Objective C code of camera implementation. Use 0.1.3 pod.
